SELAMAT PAGI, SALAM SEHAT

BERSAMA INI KAMU INFORMASIKAN MOBIL TANKI YANG AKAN SEGERA HABIS / EXPIRED MASA BERLAKU TERA :

NOPOL MT : <?= $mobil->nopol; ?>   
TRANSPORTIR : <?= $mobil->nama_transportir; ?>   
KAPASITAS : <?= $mobil->kap; ?> KL   
TANGGAL EXPIRED : <?= $tanggal_expired; ?>   


MOHON BANTUAN UNTUK DAPAT DIPERSIAPKAN DAN DIKOORDINASIKAN DENGAN MITRA KERJA DAN FUNGSI TERKAIT AGAR KEGIATAN PENYALURAN BBM / BBK DAPAT BERJALAN DENGAN OPTIMAL.

TERIMAKASIH


<?php echo $url ?>