SELAMAT PAGI, SALAM SEHAT

MASA BERLAKU <?= $kind; ?> MOBIL TANKI <?= $mobil->nopol; ?> AKAN HABIS / EXPIRED TANGGAL <?= $tanggal_expired; ?> MOHON UNTUK DAPAT SEGERA DILAKUKAN PROSES PERPANJANGAN MASA BERLAKU.

APABILA SAMPAI TANGGAL TERSEBUT BELUM ADA DOKUMEN TERBARU, MAKA MOBIL TANKI <?= $mobil->nopol; ?> TIDAK DAPAT DIOPERASIKAN UNTUK PENYALURAN BBM / BBK DARI FUEL TERMINAL REWULU KEPADA CUSTOMER.

JIKA ADA PERTANYAAN MOHON DAPAT BERKOORDINASI DENGAN BAPAK JUANDOTO (08122943460)

TERIMAKASIH